force-app/main/default/objects/Boat__c/Boat__c.object-meta.xml
<CustomObject>
    <description>This is for the Boats Object</description>
    <label>Boat</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Boat__c/fields/BoatType__c.field-meta.xml
<CustomField>
    <fullName>BoatType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Boat Type</description>
    <label>Boat Type</label>
    <referenceTo>BoatType__c</referenceTo>
    <relationshipLabel>Boats</relationshipLabel>
    <relationshipName>Boats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Boat__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Boats</relationshipLabel>
    <relationshipName>Boats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Boat__c/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <description>Picture</description>
    <label>Picture</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/BoatType__c/BoatType__c.object-meta.xml
<CustomObject>
    <label>Boat Type</label>
    <nameField>
        <label>Boat Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boat Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BoatSearchResults.cls
public with sharing class BoatSearchResults {


    @AuraEnabled
    public static List<Boat__c> getBoats(String boatTypeId){
        System.debug('Boat Id 1 ' + boatTypeId);
        //Security check to make sure that the user has access to the name field
        if ((!Schema.sObjectType.Boat__c.fields.Name.isAccessible())){
    			throw new System.NoAccessException();
    				return null;
    		}
            
        List<Boat__c> boats = new List<Boat__c>();
        System.debug('Boat Id 2 ' + boatTypeId);

        try{
            if(String.isEmpty(boatTypeId)){
                boats = [select Id,Name,Picture__c,contact__r.Name from Boat__c];
            }else{
                boats = [select Id,Name,Picture__c,contact__r.Name  from Boat__c where BoatType__c =: boatTypeId];
            }
        }catch(Exception e){
            return boats;
        }
        return boats;

    }
}